### ISSUE TITLE
Bots can't message bots. An error should show up.

### ISSUE THREAD

**Issue by Benny-** [Benny-/discordshell#25]

**Comment by Benny-** [comment]
I could not send a message from a bot to another bot. I think this is a limitation in the discord API.

Discordshell should provide some kind of feedback on this to the user.

The Discord API needs to be checked. If it is not in the docs we might file this as a bug @ discord or @ nyx ( the discord library we use )

**Comment by Torca2001** [comment]
Problem fixed, DM message button is disabled for bots
